### ISSUE TITLE
error

### ISSUE THREAD

**Issue by matrix3d** [Cleod9/as3js#1]
Analyzing package: lib3d.parser.MD5AnimBinParser
Analyzing package: lib3d.parser.MD5AnimDecoder
C:\Users\Administrator\AppData\Roaming\npm\node_modules\as3js\runtime.js:1213
                                throw new Error("Error, no closing '" + closing
- "' found for method");
                                    ^
  Error: Error, no closing '}' found for method
  at Function.OOPS.extend._statics_.extractBlock (C:\Users\Administrator\AppDa
  ta\Roaming\npm\node_modules\as3js\runtime.js:1213:11)
  at Object.OOPS.extend.parseHelper (C:\Users\Administrator\AppData\Roaming\np
  m\node_modules\as3js\runtime.js:1872:26)
  at Object.OOPS.extend.parse (C:\Users\Administrator\AppData\Roaming\npm\node
  _modules\as3js\runtime.js:2108:9)
  at Object.OOPS.extend.compile (C:\Users\Administrator\AppData\Roaming\npm\no
  de_modules\as3js\runtime.js:89:59)
  at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modul
  es\as3js\bin\as3jsc:74:25)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Function.Module.runMain (module.js:501:10)

E:\proj\my\engine\lib3d>

**Comment by Cleod9** [comment]
Thanks for reporting an issue! Are you able to share the source code MD5AnimDecoder.as? That error usually means the parser couldn't find the complete code block.

Also I'm going to improve the error output, since there is definitely more information than that I can give

**Comment by matrix3d** [comment]
https://gist.github.com/matrix3d/10339883

**Comment by Cleod9** [comment]
Thanks for sharing the code, I can see now that the problem is caused by a regular expression literal in your code that contains the `{` character. Unfortunately my parser cannot handle parsing regex literals yet, but you can get around this by using the `RegExp` constructor instead. I have updated the Readme to explain the limitation

Also note that `Embed` is not supported either, since that feature is specific to the Flash platform

**Comment by matrix3d** [comment]
所有的flash语法应该允许。即使不支持某些语法。也应该生成它。然后让用户自定义实现方式。很多字符串替换方式的语法转换器，都非常不稳定。然后不能流行。这点flexjs就是更好的实现方式了。

All of the flash grammar should be allowed.Even if they don't support some grammar.Should also generate it.And then let the user custom implementations.Many string substitution method syntax converter, are very unstable.And then can't pop.This flexjs is the better way to accomplish this.

**Comment by Cleod9** [comment]
I can agree that it would be helpful to generate code for `Embed` and let the user implement something custom. Maybe I will think of some ways to do that, but it is a low priority for me because it can be rewritten with alternative code for now.

However as for the regex support, that is just a known limitation of my parser because it is not capable of lexical analysis. I would like to implement a lexical grammar analysis on par with the AS3 language specification, but unfortunately I don't have the time to implement this in any reasonable time frame by myself :(
