### ISSUE TITLE
Please reopen this project!

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [Cleod9/as3js#18]
You were to early, this project can explode soon believe me.
please re-maintain it, a lot of developers will come soon.
thanks

**Comment by Cleod9** [comment]
Hi @ROBERT-MCDOWELL, I really appreciate the enthusiasm though this project is something that came to standstill a long time ago due to the lack of support. Unfortunately I don't have the time anymore to flesh this project out any further 😞 

If you're still interested in the subject matter though I urge you to check out this other project which aims to solve AS3->JS conversion at much more sophisticated level:
https://cwiki.apache.org/confluence/display/FLEX/FlexJS

**Comment by johnbrandle** [comment]
https://github.com/johnbrandle/as3-js

**Comment by Cleod9** [comment]
@johnbrandle Holy cow, definitely starring your project!! Where did this even come from anyway? Were you porting an AS3 project to JS?

**Comment by johnbrandle** [comment]
Thanks! Yes. We had clients who wanted mobile courses, but only had support for IE11 and Flash on their desktops due to corporate policies. Jangaroo was too limited, and this was written back in 2013 when a lot of technologies, such as Babel, did not exist. The AS3 framework I was porting was huge, and used external libraries (SWCS) and E4X, so the compiler needed to be able to handle almost every language feature...and most of the important bits of the Flash API. However, given our need, I wrote it with the assumption that something (Flex Compiler, or an IDE) would be doing a first pass over the code to check for errors....and that a majority of debugging would happen with Flash. Also, it was supposed to run in a virtual Flash Player so, I was not concerned about modifying the global scope. The project has changed a lot since I first wrote it (originally in JavaScript for use in Ant); now it is technically written in AS3 (needs a lot of refactoring), compiles with node, supports a Json SWC format, and no longer needs to be run in a virtual player. I still use this today for many node and browser-based projects, and I love it =)
