### ISSUE TITLE
Convert unsupported compound assignment

### ISSUE THREAD

**Issue by cshaa** [Cleod9/as3js#6]
Hi,
It seems that ActionScript supports some compound assignment operators that don't work in JavaScript. For example `&&=` and `||=` are the case. It's probably not hard to fix, or is it?

`( foo &&= bar ) === ( foo = foo && bar )`

Thanks for a very useful script tho,
m93a

**Comment by Cleod9** [comment]
Unfortunately this one would require an intelligent traversal of AS3's AST in order to properly transpile. Since my parser is regex-based I couldn't possibly cover all use cases to expand those expressions. This is a good find though! I didn't realize these types of assignments existed in AS3, so I'll need to update the readme
